version: '3.8'

name: doc_on_call
#kareemelbalshy
services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
