name: doc_on_call
#kareemelbalshy
services:
  app:
    build: .
    ports:
      - "3033:3033"
    environment:
      - NODE_ENV=production
      - PORT=3033
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis  # تأكد من أن خدمة التطبيق تعتمد على Redis

  redis:
    container_name: doc_redis
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
